job_board/job_board/urls.py
from django.contrib import admin
from django.urls import path, include
import requests

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("job_postings.urls")),
]

job_board/job_postings/urls.py
from django.urls import path

from . import views

app_name = "job_postings"
urlpatterns = [
    path("", views.JobListView.as_view(), name="job_postings"),
    path("create/", views.JobPostingCreateView.as_view(), name="create_posting"),
]

job_board/job_postings/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class JobPosting(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    title = models.CharField(max_length=30, default="")
    pub_date = models.DateTimeField("date published" , default=timezone.now)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    content = models.TextField()

job_board/job_postings/forms.py
from django import forms
from .models import JobPosting

class JobPostingForm(forms.ModelForm):
    class Meta:
        model = JobPosting
        fields = ['title', 'pub_date', 'category', 'content']

job_board/job_postings/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView

from .models import JobPosting, Category


class JobListView(generic.ListView):
    model = JobPosting
    template_name = "job_postings/job_postings.html"
    context_object_name = 'job_postings_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        job_postings_list = context[self.context_object_name]


        unique_categories = JobPosting.objects.values_list('category__name', flat=True).distinct()
        context['unique_categories'] = unique_categories

        selected_category = self.request.GET.get('categoryy')
        if selected_category:
            job_postings_list = job_postings_list.filter(category__name=selected_category)

        context[self.context_object_name] = job_postings_list
        return context


class JobPostingCreateView(CreateView):
    model = JobPosting
    fields = ['title',  'category', 'content']
    #form_class = JobPostingForm
    template_name = 'job_postings/create_job_posting.html'
    success_url = reverse_lazy('job_postings:job_postings')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

job_board/job_postings/templates/job_postings/create_job_posting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Job Posting</title>
</head>
<body>
    <h1>Create Job Posting</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
</body>
</html>

job_board/job_postings/templates/job_postings/job_postings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Job Postings</title>
    <style>
        body {
            margin: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            min-height: 100vh;
            position: relative;
        }

        .button {
            position: fixed;
            right: 10%;
            top: 20px;
            padding: 10px 20px;
            font-size: 16px;
            color: black;
            background-color: rgba(128, 128, 128, 0.7);
            border: none;
            border-radius: 5px;
            text-decoration: none;
            text-align: center;
            z-index: 1000;
        }

        .button:hover {
            background-color: rgba(128, 128, 128);
        }

        .container {
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: flex-start;
            width: 100%;
        }

        .table-container {
            width: 400px;
            max-width: 400px;

            margin: 20px;
            padding: 20px;
        }

        .table-container ul {
            list-style: none;
            padding: 0;
        }

        .table-container div {
            margin-bottom: 20px;
        }

        .table-container hr {
            width: 90%;
            margin-left: auto;
            margin-right: 30px;
        }
    </style>
</head>
<body>


    <a href="{% url 'job_postings:create_posting' %}" class="button">Create Job Posting</a>
    <div class="container">
    <form method="get">
        <select name="categoryy">
            <option value="">All Categories</option>
            {% for category in unique_categories %}
                <option value= "{{ category }}" {% if category == request.GET.category %}selected{% endif %}>{{ category }}</option>
            {% endfor %}
        </select>
        <button type="submit">Filter</button>
    </form>

    <div class="table-container">
        {% if job_postings_list %}
            <ul>
            {% for posting in job_postings_list %}
                <div style="background-color: rgba(128, 128, 128, 0.45); padding: 20px; border-radius: 10px">
                    <pre>Posted: {{ posting.pub_date }}</pre>
                    <pre>By: {{ posting.user }}</pre>
                    <h3 style="word-wrap: break-word;">{{ posting.title }}</h3>
                    <pre style="white-space: pre-wrap; word-wrap: break-word;">{{ posting.content }}</pre>
                </div>
            {% endfor %}
            </ul>
        {% else %}
            <p>No job postings are available.</p>
        {% endif %}
    </div>
</div>
</body>
</html>